"""
LLM-as-a-judge reward module for caption RL (baseline A).

Drop-in helper that can be imported into text2mask.py.
The judge LLM is served by an external vLLM instance (OpenAI-compatible HTTP).
This module never owns GPU memory.

Usage in text2mask.py
---------------------
1) At the top of text2mask.py, add:
       from llm_judge_reward import (
           init_judge_clients,
           compute_caption_judge_rewards_batch,
       )
       init_judge_clients()

2) Inside compute_score, BEFORE the per-sample for-loop, batch-compute all
   dam_captioning rewards in one shot:

       dam_indices = [
           i for i, ri in enumerate(reward_inputs)
           if ri["source"] == "dam_captioning"
       ]
       if dam_indices:
           dam_rewards = compute_caption_judge_rewards_batch(
               [reward_inputs[i]["response"]         for i in dam_indices],
               [reward_inputs[i]["cap_ground_truth"] for i in dam_indices],
           )
           dam_reward_map = dict(zip(dam_indices, dam_rewards))
       else:
           dam_reward_map = {}

3) In the dam_captioning branch of the for-loop:

       elif source in ['dam_captioning']:
           caption_reward = dam_reward_map[i]   # i is the loop index
           scores.append({
               "cap_overall":     caption_reward,
               "caption_reward":  caption_reward,
           })
"""

import asyncio
import os
import random
import re
from typing import List, Optional

from openai import AsyncOpenAI


# =====================================================================
# Prompt — reuse the one you already have in text2mask.py.
# Kept here verbatim for self-containedness; feel free to import instead.
# =====================================================================
CAPTION_REWARD_PROMPT = """# ROLE
You are a strict reward model judge for grounded image captions.

# INPUTS
You will be given:
(1) A ground-truth caption (GT), written in grounded-conversation caption style.
(2) A rollout caption (ROLL), generated by a policy model, using special tokens:
- <|object_ref_start|> ... <|object_ref_end|> wraps a referred phrase.
- <|mt_start|> <|mt_xxxx|> <|mt_yyyy|> <|mt_end|> is the mask token span for that phrase.
These special tokens are allowed and should NOT be treated as grammatical errors.

# OBJECTIVE
Output a single boolean judgement indicating caption quality:
- true  : the rollout caption is a fluent, natural sentence AND captures the main visual content of the image, consistent with GT.
- false : otherwise.

# EVALUATION CRITERIA (ALL MUST PASS FOR true)
A. Fluency & Naturalness (mandatory)
- The rollout caption must read as a coherent, natural image caption.
- It must NOT degenerate into list-style or recall-driven enumeration.
- Minor grammatical imperfections are acceptable; fragmented, repetitive, or template-like constructions are not.

B. Main Content Alignment with GT (mandatory)
- Compare the rollout caption with GT at the level of core semantics:
  main subject(s), main action(s), and overall scene.
- Different wording or level of detail is allowed.
- Missing the primary event, contradicting it, or focusing mainly on secondary details ⇒ false.
- Introducing major hallucinated actions or scenes not implied by GT ⇒ false.

C. Grounded Caption Usage (soft constraint)
- The use of <|object_ref_start|> ... <|object_ref_end|> and mask token spans is valid.
- However, abusing these tokens to stack many weakly-related phrases without forming a coherent sentence
  should be judged as failing fluency.

# OUTPUT FORMAT (STRICT)
Output ONLY one lowercase word:
- true
- false

Do NOT output numbers, symbols, punctuation, explanations, or additional text.

# DATA
## Ground Truth Caption (GT)
{gt_caption}

## Rollout Caption (ROLL)
{rollout_caption}

# FINAL JUDGEMENT
Answer:"""


# =====================================================================
# Global client pool (matches the multi-endpoint pattern you had before)
# =====================================================================
_ASYNC_CLIENTS: List[AsyncOpenAI] = []
_MODEL_NAMES: List[str] = []


def init_judge_clients(
    api_bases: Optional[List[str]] = None,
    api_key: Optional[str] = None,
    model_name: Optional[str] = None,
) -> None:
    """
    Initialize the async OpenAI clients pointing at one or more vLLM servers.

    Call this ONCE at module import time, not per-rollout.
    Reads from env vars by default so config lives in your launch script:
        LLM_AS_A_JUDGE_BASES   "http://host1:18901/v1,http://host2:18901/v1"
        LLM_AS_A_JUDGE_KEY     "EMPTY" or your real key
        LLM_AS_A_JUDGE_MODEL   "qwen-judge"
    """
    global _ASYNC_CLIENTS, _MODEL_NAMES

    if api_bases is None:
        env = os.environ.get(
            "LLM_AS_A_JUDGE_BASES",
            os.environ.get("LLM_AS_A_JUDGE_BASE", "http://127.0.0.1:18901/v1"),
        )
        api_bases = [b.strip() for b in env.split(",") if b.strip()]
    if api_key is None:
        api_key = os.environ.get("LLM_AS_A_JUDGE_KEY", "EMPTY")
    if model_name is None:
        model_name = os.environ.get("LLM_AS_A_JUDGE_MODEL", "qwen-judge")

    _ASYNC_CLIENTS = [
        AsyncOpenAI(api_key=api_key, base_url=base, timeout=60.0, max_retries=2)
        for base in api_bases
    ]
    _MODEL_NAMES = [model_name] * len(_ASYNC_CLIENTS)
    print(f"[llm_judge_reward] initialized {len(_ASYNC_CLIENTS)} judge endpoint(s): {api_bases}")


# =====================================================================
# Single-sample async call
# =====================================================================
def _parse_judgement(text: str) -> Optional[bool]:
    """Parse the judge's `true` / `false` answer."""
    if not isinstance(text, str):
        return None
    # Strip markdown / punctuation, take last decisive token
    t = text.strip().lower()
    # Allow it to follow your previous "## Equivalence Judgement" tail format too
    if "## equivalence judgement" in t:
        t = t.split("## equivalence judgement")[-1]
    has_true = bool(re.search(r"\btrue\b", t))
    has_false = bool(re.search(r"\bfalse\b", t))
    if has_true and not has_false:
        return True
    if has_false and not has_true:
        return False
    return None


async def _judge_one(
    response: str,
    gt: str,
    semaphore: asyncio.Semaphore,
    max_votes: int = 1,
    temperature: float = 0.0,
) -> float:
    """
    Reward for a single (response, gt) pair.

    Returns a float in [0, 1]:
        1.0 if judge says "true"
        0.0 if judge says "false" or any failure (conservative: failure = bad)

    Setting max_votes > 1 enables your previous self-consistency style: sample
    multiple times with temperature > 0 and majority-vote. Defaults to 1 with
    temperature=0 for a clean, reproducible baseline (recommended).
    """
    if not isinstance(response, str) or len(response.strip()) == 0:
        return 0.0

    prompt = CAPTION_REWARD_PROMPT.format(
        gt_caption=gt.strip(),
        rollout_caption=response.strip(),
    )

    votes: List[bool] = []
    async with semaphore:
        for _ in range(max_votes):
            # Round-robin over endpoints to spread load
            idx = random.randint(0, len(_ASYNC_CLIENTS) - 1)
            client = _ASYNC_CLIENTS[idx]
            model_name = _MODEL_NAMES[idx]
            try:
                completion = await client.chat.completions.create(
                    model=model_name,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=temperature,
                    max_tokens=10,   # only need "true"/"false"
                )
                raw = completion.choices[0].message.content
                verdict = _parse_judgement(raw)
                if verdict is not None:
                    votes.append(verdict)
                    if max_votes == 1:
                        break
                    # Early exit on first-decisive style (matches your previous code)
                    # Comment this out if you want pure majority vote.
                    if len(votes) >= 2 and votes[-1] == votes[-2]:
                        break
            except Exception as e:
                # Don't kill the whole batch — log and treat as unparseable
                print(f"[llm_judge_reward] judge call failed: {e}")
                continue

    if not votes:
        return 0.0
    # Majority vote (or single vote if max_votes==1)
    return 1.0 if sum(votes) > len(votes) / 2 else 0.0


# =====================================================================
# Public batch entry point — call this from compute_score
# =====================================================================
def compute_caption_judge_rewards_batch(
    responses: List[str],
    gts: List[str],
    max_concurrency: int = 64,
    max_votes: int = 1,
    temperature: float = 0.0,
) -> List[float]:
    """
    Compute LLM-judge rewards for a whole rollout batch in parallel.

    Args:
        responses: list of rollout captions
        gts:       list of GT captions (same length)
        max_concurrency: cap concurrent in-flight requests to the judge server.
            Set this <= the judge vLLM's effective batch capacity. 64 is safe
            for a single 72B-on-4xH100 vLLM with --max-num-seqs 256.
        max_votes: 1 = single deterministic call (recommended baseline).
            Set >1 with temperature>0 for self-consistency voting.
        temperature: judge sampling temperature. 0.0 for reproducibility.

    Returns:
        list of float rewards in [0, 1], same length as inputs.
    """
    assert len(responses) == len(gts), "responses and gts length mismatch"
    if not _ASYNC_CLIENTS:
        raise RuntimeError(
            "Judge clients not initialized. Call init_judge_clients() first."
        )
    if len(responses) == 0:
        return []

    async def _run_all():
        sem = asyncio.Semaphore(max_concurrency)
        tasks = [
            _judge_one(r, g, sem, max_votes=max_votes, temperature=temperature)
            for r, g in zip(responses, gts)
        ]
        return await asyncio.gather(*tasks)

    # verl's reward function is called from a sync context (Ray worker).
    # asyncio.run is fine here — there's no running loop in that worker.
    try:
        return asyncio.run(_run_all())
    except RuntimeError:
        # Fallback for the rare case where an event loop already exists
        # (shouldn't happen in standard verl, but be defensive)
        loop = asyncio.new_event_loop()
        try:
            return loop.run_until_complete(_run_all())
        finally:
            loop.close()